# Generated by Django 4.2.7 on 2024-06-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0002_blogpost_main_description_blogpost_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
